[package]
name = "wmi"
version = "0.4.4"
authors = ["Ohad Ravid <ohad.rv@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/crate/wmi"
homepage = "https://github.com/ohadravid/wmi-rs"
repository = "https://github.com/ohadravid/wmi-rs"
description = """
WMI crate for rust.
"""
categories = ["api-bindings", "os::windows-apis"]
keywords = ["wmi", "com", "win32"]

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"

[features]
test = ["lazy_static"]

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3.7", features = ["objbase", "wbemcli", "objidlbase", "oaidl", "oleauto", "errhandlingapi"] }
failure = "0.1.5"
log = "0.4.8"
widestring = "0.4"
serde = { version = "1.0.98", features = ["derive"] }
chrono = { version = "0.4.7", features = ["serde"] }
lazy_static = { version = "1.3.0", optional = true }

[build-dependencies]
little-skeptic = "0.15.2"

[dev-dependencies]
lazy_static = "1.3.0"
serde_json = { version = "1.0.40" }
criterion = "0.2.11"
little-skeptic = "0.15.2"

[[bin]]
name = "wmiq"

[[bench]]
name = "benchmark"
path = "./src/benches/benchmark.rs"
harness = false